In [1]:
# Rather than using the basic model, we here compute based on the Term-Frequency Inverse-Document-Frequency (TFIDF)
# This means that words that have low semantic meaning are downprioritised in weighing
# In practice this would be better for longer texts perhaps?
import numpy as np
import pandas as pd
from sklearn import *

In [11]:
# Get data
test_df = pd.read_csv("../0-Data/test.csv")
train_df = pd.read_csv("../0-Data/train.csv")

# Make into vectors
vectorizer = feature_extraction.text.TfidfVectorizer()
train_vec = vectorizer.fit_transform(train_df["text"])
test_vec = vectorizer.transform(test_df["text"])

In [14]:
# Inspect results
print(train_vec[0].todense().shape)
print(train_vec[0].todense())

(1, 21637)
[[0. 0. 0. ... 0. 0. 0.]]


matrix([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]])

In [5]:
# Build model
clf = linear_model.RidgeClassifier()
scores = model_selection.cross_val_score(clf, train_vec, train_df["target"], cv=3, scoring="f1")
scores

array([0.63366337, 0.6122449 , 0.68442211])

In [10]:
# Build submission
clf.fit(train_vec, train_df["target"])
sample_sub = pd.read_csv("../0-Data/sample_submission.csv")
sample_sub["target"] = clf.predict(test_vec)
sample_sub.head()

id  target
0   0       1
1   2       1
2   3       1
3   9       0
4  11       1

In [ ]:
# Make into csv
sample_sub.to_csv("../0-Data/submission.csv", index = False)